/***************************************************************************************
**文件名:     Menu_DataStructure.c
**版本:       V1.00
**说明:       此文件可以根据实际情况修改。
**修改记录:   
*版本:V1.00     
*修改者:hhx    
*时间:
*修改说明：                    
创建了这个文件 
**备注:      
****************************************************************************************/
#include "menu.h"
#include "Menu_CurrentOperate.h"
#if MENU_MODULE_EN
/*************************.C变量结构声明***********************/

/*************************私有全局变量*************************/
const static TYPEe_MenuIndex a_SubMenu_Admin[] = {
    enum_Menu_FaceSet,         //人脸信息设置
    enum_Menu_FingerSet,       //指纹信息设置
    enum_Menu_ModPwd,          //密码设置
    enum_Menu_MotorTorsionSet, //电机扭力调节
    enum_Menu_VioceSet,        //音量设置
    enum_Menu_AdminReturn,     //主菜单退出
};
const static TYPEe_MenuIndex a_SubMenu_FaceSet[] = {
    enum_Menu_AddAdminFace,   //增加管理员人脸
    enum_Menu_AddGeneralFace, //增加普通人脸
    enum_Menu_DelGeneralFace, //删除普通用户人脸
    enum_Menu_FaceSetReturn,  //人脸识别菜单返回
};
const static TYPEe_MenuIndex a_SubMenu_FingerSet[] = {
    enum_Menu_AddGeneralFinger, //增加普通指纹
    enum_Menu_DelFinger,        //删除指纹
    enum_Menu_FingerSetReturn,  //指纹信息设置返回
};
const static TYPEe_MenuIndex a_SubMenu_MotorTorsionSet[] = {
    enum_Menu_MotorTorsionLow,       //低电机扭力
    enum_Menu_MotorTorsionHigh,      //高电机扭力
    enum_Menu_MotorTorsionSetReturn, //电机扭力调节返回
};
const static TYPEe_MenuIndex a_SubMenu_VioceSet[] = {
    enum_Menu_VioceClose,     //关闭语音
    enum_Menu_VioceOpen,      //打开语音
    enum_Menu_VioceSetReturn, //音量设置返回
};
/*************************公共全局变量*************************/

/***************************************************************************/ /**
 * @brief
 *   该菜单数据结构的顺序必需同枚举类型TYPEe_MenuIndex严格相同
 *
 ******************************************************************************/
const TYPEs_KbdTabStruct struct_MenuTab[enum_Menu_MAX] =
    {
        [enum_Menu_SystemSleep] = {enum_Menu_SystemSleep,
                                   enum_Menu_Welcome,
                                   enum_Window_NoResponseNotify,
                                   M_MENU_DISPLAY_TIMER_FOREVER,
                                   0,
                                   NULL,
                                   (*Menu_SystemSleep)}, //系统休眠
        [enum_Menu_BackDeal] = {enum_Menu_BackDeal,
                                enum_Menu_Welcome,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_FOREVER,
                                0,
                                NULL,
                                (*Menu_SystemSleep)}, //系统完全进入休眠
        [enum_Menu_WakeUp] = {enum_Menu_WakeUp,
                              enum_Menu_SystemSleep,
                              enum_Window_NoResponseNotify,
                              M_MENU_DISPLAY_TIMER_LEVEL_10,
                              0,
                              NULL,
                              (*Menu_SystemSleep)}, //系统唤醒处理
        [enum_Menu_LowPower] = {enum_Menu_LowPower,
                                enum_Menu_Desktop,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_3,
                                0,
                                NULL,
                                (*Menu_SystemSleep)}, //电量低
        [enum_Menu_LowPowerCannotWrok] = {enum_Menu_LowPowerCannotWrok,
                                          enum_Menu_SystemSleep,
                                          enum_Window_NoResponseNotify,
                                          M_MENU_DISPLAY_TIMER_LEVEL_3,
                                          0,
                                          NULL,
                                          (*Menu_SystemSleep)}, //电量低，无法工作
        [enum_Menu_StorageError] = {enum_Menu_StorageError,
                                    enum_Menu_SystemSleep,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_3,
                                    0,
                                    NULL,
                                    (*Menu_SystemSleep)}, //电量低，无法工作
        [enum_Menu_Welcome] = {enum_Menu_Welcome,
                               enum_Menu_Desktop,
                               enum_Window_Notify,
                               M_MENU_DISPLAY_TIMER_LEVEL_1, //1S
                               0,
                               NULL,
                               (*Menu_Welcome)}, //欢迎画面
        [enum_Menu_Desktop] = {enum_Menu_Desktop,
                               enum_Menu_Desktop,
                               enum_Window_TopDialog,
								//								M_MENU_DISPLAY_TIMER_LEVEL_20,
								//                               M_MENU_DISPLAY_TIMER_LEVEL_10,
								//                               M_MENU_DISPLAY_TIMER_LEVEL_2, //
								#if 0
								M_MENU_DISPLAY_TIMER_LEVEL_20,
								#endif
								#if 0
								M_MENU_DISPLAY_TIMER_LEVEL_10,
								#endif
								#if 0
								M_MENU_DISPLAY_TIMER_FOREVER, //暂时永远不退出。
								#endif
                                 M_MENU_DISPLAY_TIMER_LEVEL_20,
                               0,
                               NULL,
                               (*Menu_Desktop)}, //桌面
        [enum_Menu_FirstUse] = {enum_Menu_FirstUse,
                                enum_Menu_FirstUse,
                                enum_Window_TopDialog,
                                M_MENU_DISPLAY_TIMER_LEVEL_4,
                                0,
                                NULL,
                                (*Menu_FirstUse)}, //首次使用
        [enum_Menu_PassWdPass] = {enum_Menu_PassWdPass,
                                  enum_Menu_BackDeal,
                                  enum_Window_NoResponseNotify,
                                  M_MENU_DISPLAY_TIMER_LEVEL_15,
                                  0,
                                  NULL,
                                  (*Menu_PassWdPass)}, //密码正确
        [enum_Menu_PassWdFail] = {enum_Menu_PassWdFail,
                                  enum_Menu_SystemSleep,
                                  enum_Window_NoResponseNotify,
                                  M_MENU_DISPLAY_TIMER_LEVEL_2, //2S
                                  0,
                                  NULL,
                                  (*Menu_PassWdFail)}, //密码错误
        [enum_Menu_TryFingerVerifyOK] = {enum_Menu_TryFingerVerifyOK,
                                         enum_Menu_BackDeal,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_15,
                                         0,
                                         NULL,
                                         (*Menu_PassWdFail)}, //试用模式通过
        [enum_Menu_AdminChk] = {enum_Menu_AdminChk,
                                enum_Menu_SystemSleep,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_20, //
                                0,
                                NULL,
                                (*Menu_PassWdFail)}, //进入管理菜单检查
        [enum_Menu_AdminChkFail] = {enum_Menu_AdminChkFail,
                                enum_Menu_SystemSleep,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_2, //
                                0,
                                NULL,
                                (*Menu_None)}, //校验失败 
        [enum_Menu_Admin] = {enum_Menu_Admin,
                             enum_Menu_SystemSleep,
                             enum_Window_Menu,
                             M_MENU_DISPLAY_TIMER_LEVEL_20,
                             sizeof(a_SubMenu_Admin) / sizeof(TYPEe_MenuIndex),
                             a_SubMenu_Admin,
                             (*Menu_None)}, //管理菜单
        [enum_Menu_AdminReturn] = {enum_Menu_AdminReturn,
                                   enum_Menu_SystemSleep,
                                   enum_Window_GeneralDialog,
                                   M_MENU_DISPLAY_TIMER_LEVEL_1,
                                   0,
                                   NULL,
                                   (*Menu_None)}, //主菜单退出
        [enum_Menu_FaceSet] = {enum_Menu_FaceSet,
                               enum_Menu_Admin,
                               enum_Window_Menu,
                               M_MENU_DISPLAY_TIMER_LEVEL_15,
                               sizeof(a_SubMenu_FaceSet) / sizeof(TYPEe_MenuIndex),
                               a_SubMenu_FaceSet,
                               (*Menu_None)}, //人脸信息设置
        [enum_Menu_AddAdminFace] = {enum_Menu_AddAdminFace,
                                    enum_Menu_FaceSet,
                                    enum_Window_GeneralDialog,
                                    M_MENU_DISPLAY_TIMER_LEVEL_10,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //增加管理员人脸
        [enum_Menu_AddGeneralFace] = {enum_Menu_AddGeneralFace,
                                      enum_Menu_FaceSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //增加普通人脸
        [enum_Menu_DelGeneralFace] = {enum_Menu_DelGeneralFace,
                                      enum_Menu_FaceSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //删除普通用户人脸
        [enum_Menu_FaceSetReturn] = {enum_Menu_FaceSetReturn,
                                     enum_Menu_Admin,
                                     enum_Window_GeneralDialog,
                                     M_MENU_DISPLAY_TIMER_LEVEL_4,
                                     0,
                                     NULL,
                                     (*Menu_None)}, //人脸识别菜单返回
        [enum_Menu_AddAdminFaceFull] = {enum_Menu_AddAdminFaceFull,
                                        enum_Menu_FaceSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)}, //管理人脸已满
        [enum_Menu_AddGeneralFaceFull] = {enum_Menu_AddGeneralFaceFull,
                                          enum_Menu_FaceSet,
                                          enum_Window_GeneralDialog,
                                          M_MENU_DISPLAY_TIMER_LEVEL_4,
                                          0,
                                          NULL,
                                          (*Menu_None)}, //普通人脸已满
        [enum_Menu_AddFaceStep1] = {enum_Menu_AddFaceStep1,
                                    enum_Menu_FaceSet,
                                    enum_Window_OnlyReturn,
                                    M_MENU_DISPLAY_TIMER_LEVEL_20,
                                    0,
                                    NULL,
                                    (*Menu_None)},
        [enum_Menu_AddFaceStep1OK] = {enum_Menu_AddFaceStep1OK,
                                      enum_Menu_FaceSet,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_6,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //添加人脸过程成功

        [enum_Menu_AddFaceStep2] = {enum_Menu_AddFaceStep2,
                                    enum_Menu_FaceSet,
                                    enum_Window_OnlyReturn,
                                    M_MENU_DISPLAY_TIMER_LEVEL_20,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //添加人脸过程

        [enum_Menu_AddFaceStep2OK] = {enum_Menu_AddFaceStep2OK,
                                      enum_Menu_FaceSet,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_6,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //添加人脸过程成功

        [enum_Menu_AddFaceStep3] = {enum_Menu_AddFaceStep3,
                                    enum_Menu_FaceSet,
                                    enum_Window_OnlyReturn,
                                    M_MENU_DISPLAY_TIMER_LEVEL_20,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //添加人脸过程

        [enum_Menu_AddFaceStep3OK] = {enum_Menu_AddFaceStep3OK,
                                      enum_Menu_FaceSet,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_6,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //添加人脸过程成功

        [enum_Menu_AddFaceStep4] = {enum_Menu_AddFaceStep4,
                                    enum_Menu_FaceSet,
                                    enum_Window_OnlyReturn,
                                    M_MENU_DISPLAY_TIMER_LEVEL_20,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //添加人脸过程

        [enum_Menu_AddFaceStep4OK] = {enum_Menu_AddFaceStep4OK,
                                      enum_Menu_FaceSet,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_6,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //添加人脸过程成功

        [enum_Menu_AddFaceStep5] = {enum_Menu_AddFaceStep5,
                                    enum_Menu_FaceSet,
                                    enum_Window_OnlyReturn,
                                    M_MENU_DISPLAY_TIMER_LEVEL_20,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //添加人脸过程

        [enum_Menu_AddFaceStep5OK] = {enum_Menu_AddFaceStep5OK,
                                      enum_Menu_FaceSet,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_6,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //添加人脸过程5成功

        [enum_Menu_AddFaceUserOk] = {enum_Menu_AddFaceUserOk,
                                     enum_Menu_FaceSet,
                                     enum_Window_NoResponseNotify,
                                     M_MENU_DISPLAY_TIMER_LEVEL_2,
                                     0,
                                     NULL,
                                     (*Menu_None)}, //添加人脸成功

        [enum_Menu_AddFaceUserFail] = {enum_Menu_AddFaceUserFail,
                                       enum_Menu_FaceSet,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_2,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //添加人脸失败

        [enum_Menu_FaceVerifyOk] = {enum_Menu_FaceVerifyOk,
                                    enum_Menu_SystemSleep,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_15,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //人脸验证成功

        [enum_Menu_FaceVerifyFail] = {enum_Menu_FaceVerifyFail,
                                      enum_Menu_Desktop,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_2,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //人脸验证失败
		[enum_Menu_FaceVerifyRetry] = {enum_Menu_FaceVerifyRetry,
                                      enum_Menu_Desktop,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_4,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //重新验证人脸
        [enum_Menu_DelGeneralFaceOK] = {enum_Menu_DelGeneralFaceOK,
                                        enum_Menu_FaceSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)}, //删除普通成功

        [enum_Menu_DelGeneralFaceFail] = {enum_Menu_DelGeneralFaceFail,
                                          enum_Menu_FaceSet,
                                          enum_Window_Notify,
                                          M_MENU_DISPLAY_TIMER_LEVEL_2,
                                          0,
                                          NULL,
                                          (*Menu_None)}, //删除普通用户成功
        [enum_Menu_FaceNotDetected] = {enum_Menu_FaceNotDetected,
                                       enum_Menu_SystemSleep,
                                       enum_Window_Notify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_2,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //未检测到人脸
        [enum_Menu_MotorTorsionSet] = {enum_Menu_MotorTorsionSet,
                                       enum_Menu_Admin,
                                       enum_Window_Menu,
                                       M_MENU_DISPLAY_TIMER_LEVEL_15,
                                       sizeof(a_SubMenu_MotorTorsionSet) / sizeof(TYPEe_MenuIndex),
                                       a_SubMenu_MotorTorsionSet,
                                       (*Menu_None)}, //电机扭力调节
        [enum_Menu_MotorTorsionLow] = {enum_Menu_MotorTorsionLow,
                                       enum_Menu_Admin,
                                       enum_Window_GeneralDialog,
                                       M_MENU_DISPLAY_TIMER_LEVEL_10,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //低电机扭力
        [enum_Menu_MotorTorsionHigh] = {enum_Menu_MotorTorsionHigh,
                                        enum_Menu_Admin,
                                        enum_Window_GeneralDialog,
                                        M_MENU_DISPLAY_TIMER_LEVEL_10,
                                        0,
                                        NULL,
                                        (*Menu_None)}, //高电机扭力

        [enum_Menu_MotorTorsionSetReturn] = {enum_Menu_MotorTorsionSetReturn,
                                             enum_Menu_Admin,
                                             enum_Window_GeneralDialog,
                                             M_MENU_DISPLAY_TIMER_LEVEL_4,
                                             0,
                                             NULL,
                                             (*Menu_None)}, //电机扭力调节返回
        [enum_Menu_MotorTorsionSetOk] = {enum_Menu_MotorTorsionSetOk,
                                         enum_Menu_Admin,
                                         enum_Window_Notify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_2,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //电机扭力调节设定成功
        [enum_Menu_VioceSet] = {enum_Menu_VioceSet,
                                enum_Menu_Admin,
                                enum_Window_Menu,
                                M_MENU_DISPLAY_TIMER_LEVEL_15,
                                sizeof(a_SubMenu_VioceSet) / sizeof(TYPEe_MenuIndex),
                                a_SubMenu_VioceSet,
                                (*Menu_None)}, //音量设置
        [enum_Menu_VioceClose] = {enum_Menu_VioceClose,
                                  enum_Menu_Admin,
                                  enum_Window_GeneralDialog,
                                  M_MENU_DISPLAY_TIMER_LEVEL_10,
                                  0,
                                  NULL,
                                  (*Menu_None)}, //关闭语音

        [enum_Menu_VioceOpen] = {enum_Menu_VioceOpen,
                                 enum_Menu_Admin,
                                 enum_Window_GeneralDialog,
                                 M_MENU_DISPLAY_TIMER_LEVEL_10,
                                 0,
                                 NULL,
                                 (*Menu_None)}, //打开语音
        [enum_Menu_VioceSetReturn] = {enum_Menu_VioceSetReturn,
                                      enum_Menu_Admin,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_4,
                                      0,
                                      NULL,
                                      (*Menu_None)}, //音量设置返回
        [enum_Menu_VioceSetOk] = {enum_Menu_VioceSetOk,
                                  enum_Menu_Admin,
                                  enum_Window_Notify,
                                  M_MENU_DISPLAY_TIMER_LEVEL_2,
                                  0,
                                  NULL,
                                  (*Menu_None)}, //语音设置成功
        [enum_Menu_ModPwd] = {enum_Menu_ModPwd,
                              enum_Menu_Admin,
                              enum_Window_GeneralDialog,
                              M_MENU_DISPLAY_TIMER_LEVEL_15,
                              0,
                              NULL,
                              (*Menu_None)}, //修改密码
        [enum_Menu_ModPwdInputAgain] = {enum_Menu_ModPwdInputAgain,
                                        enum_Menu_Admin,
                                        enum_Window_GeneralDialog,
                                        M_MENU_DISPLAY_TIMER_LEVEL_15,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_ModPwdOk] = {enum_Menu_ModPwdOk,
                                enum_Menu_Admin,
                                enum_Window_Notify,
                                M_MENU_DISPLAY_TIMER_LEVEL_2,
                                0,
                                NULL,
                                (*Menu_None)},

        [enum_Menu_ModPwdFail] = {enum_Menu_ModPwdFail,
                                  enum_Menu_Admin,
                                  enum_Window_Notify,
                                  M_MENU_DISPLAY_TIMER_LEVEL_4,
                                  0,
                                  NULL,
                                  (*Menu_None)},

        [enum_Menu_ModPwdTooSimpleFail] = {enum_Menu_ModPwdTooSimpleFail,
                                           enum_Menu_Admin,
                                           enum_Window_Notify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_FingerSet] = {enum_Menu_FingerSet,
                                 enum_Menu_Admin,
                                 enum_Window_Menu,
                                 M_MENU_DISPLAY_TIMER_LEVEL_15,
                                 sizeof(a_SubMenu_FingerSet) / sizeof(TYPEe_MenuIndex),
                                 a_SubMenu_FingerSet,
                                 (*Menu_None)}, //指纹信息设置
        [enum_Menu_AddFinger] = {enum_Menu_AddFinger,
                                 enum_Menu_FingerSet,
                                 enum_Window_GeneralDialog,
                                 M_MENU_DISPLAY_TIMER_LEVEL_4,
                                 0,
                                 NULL,
                                 (*Menu_None)},
        [enum_Menu_DelFinger] = {enum_Menu_DelFinger,
                                 enum_Menu_FingerSet,
                                 enum_Window_GeneralDialog,
                                 M_MENU_DISPLAY_TIMER_LEVEL_10,
                                 0,
                                 NULL,
                                 (*Menu_None)},
        [enum_Menu_FingerSetReturn] = {enum_Menu_FingerSetReturn,
                                       enum_Menu_FingerSet,
                                       enum_Window_GeneralDialog,
                                       M_MENU_DISPLAY_TIMER_LEVEL_10,
                                       0,
                                       NULL,
                                       (*Menu_None)},
        [enum_Menu_AddAdminFinger] = {enum_Menu_AddAdminFinger,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_4,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_AddGeneralFinger] = {enum_Menu_AddGeneralFinger,
                                        enum_Menu_FingerSet,
                                        enum_Window_GeneralDialog,
                                        M_MENU_DISPLAY_TIMER_LEVEL_10,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_AddFingerReturn] = {enum_Menu_AddFingerReturn,
                                       enum_Menu_Admin,
                                       enum_Window_GeneralDialog,
                                       M_MENU_DISPLAY_TIMER_LEVEL_4,
                                       0,
                                       NULL,
                                       (*Menu_None)},

        [enum_Menu_AddAdminFingerFull] = {enum_Menu_AddAdminFingerFull,
                                          enum_Menu_FingerSet,
                                          enum_Window_Notify,
                                          M_MENU_DISPLAY_TIMER_LEVEL_2,
                                          0,
                                          NULL,
                                          (*Menu_None)},

        [enum_Menu_AddGeneralFingerFull] = {enum_Menu_AddGeneralFingerFull,
                                            enum_Menu_FingerSet,
                                            enum_Window_Notify,
                                            M_MENU_DISPLAY_TIMER_LEVEL_2,
                                            0,
                                            NULL,
                                            (*Menu_None)},

        [enum_Menu_DelFingerOk] = {enum_Menu_DelFingerOk,
                                   enum_Menu_FingerSet,
                                   enum_Window_GeneralDialog,
                                   M_MENU_DISPLAY_TIMER_LEVEL_2,
                                   0,
                                   NULL,
                                   (*Menu_None)},

        [enum_Menu_DelFingerFail] = {enum_Menu_DelFingerFail,
                                     enum_Menu_Admin,
                                     enum_Window_GeneralDialog,
                                     M_MENU_DISPLAY_TIMER_LEVEL_2,
                                     0,
                                     NULL,
                                     (*Menu_None)},

        [enum_Menu_DelFingerNoneFail] = {enum_Menu_DelFingerNoneFail,
                                         enum_Menu_Admin,
                                         enum_Window_GeneralDialog,
                                         M_MENU_DISPLAY_TIMER_LEVEL_1,
                                         0,
                                         NULL,
                                         (*Menu_None)},

        [enum_Menu_AddFingerStep1] = {enum_Menu_AddFingerStep1,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_AddFingerStep1OK] = {enum_Menu_AddFingerStep1OK,
                                        enum_Menu_FingerSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_4,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_AddFingerStep2] = {enum_Menu_AddFingerStep2,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_AddFingerStep2OK] = {enum_Menu_AddFingerStep2OK,
                                        enum_Menu_FingerSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_4,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_AddFingerStep3] = {enum_Menu_AddFingerStep3,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_AddFingerStep3OK] = {enum_Menu_AddFingerStep3OK,
                                        enum_Menu_FingerSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_4,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_AddFingerStep4] = {enum_Menu_AddFingerStep4,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_AddFingerStep4OK] = {enum_Menu_AddFingerStep4OK,
                                        enum_Menu_FingerSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_4,
                                        0,
                                        NULL,
                                        (*Menu_None)},
        [enum_Menu_AddFingerStep5] = {enum_Menu_AddFingerStep5,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},
        [enum_Menu_AddFingerStep5OK] = {enum_Menu_AddFingerStep5OK,
                                        enum_Menu_FingerSet,
                                        enum_Window_Notify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_4,
                                        0,
                                        NULL,
                                        (*Menu_None)},
        [enum_Menu_AddFingerStep6] = {enum_Menu_AddFingerStep6,
                                      enum_Menu_FingerSet,
                                      enum_Window_GeneralDialog,
                                      M_MENU_DISPLAY_TIMER_LEVEL_10,
                                      0,
                                      NULL,
                                      (*Menu_None)},
        [enum_Menu_AddFingerUserOk] = {enum_Menu_AddFingerUserOk,
                                       enum_Menu_FingerSet,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_3,
                                       0,
                                       NULL,
                                       (*Menu_None)},

        [enum_Menu_AddFingerUserFail] = {enum_Menu_AddFingerUserFail,
                                         enum_Menu_FingerSet,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_2,
                                         0,
                                         NULL,
                                         (*Menu_None)},

        [enum_Menu_Factory] = {enum_Menu_Factory,
                               enum_Menu_SystemSleep,
                               enum_Window_GeneralDialog,
                               M_MENU_DISPLAY_TIMER_LEVEL_10,
                               0,
                               NULL,
                               (*Menu_None)},
		[enum_Menu_FactoryConfirm] = { enum_Menu_FactoryConfirm,
									   enum_Menu_FactoryIng,
									   enum_Window_NoResponseNotify,
									   M_MENU_DISPLAY_TIMER_LEVEL_2,
									   0,
									   NULL,
									   (*Menu_None)},
        [enum_Menu_FactoryIng] = {enum_Menu_FactoryIng,
                                  enum_Menu_SystemSleep,
                                  enum_Window_NoResponseNotify,
                                  M_MENU_DISPLAY_TIMER_LEVEL_10,
                                  0,
                                  NULL,
                                  (*Menu_None)},

        [enum_Menu_FactoryOK] = {enum_Menu_FactoryOK,
                                 enum_Menu_SystemSleep,
                                 enum_Window_NoResponseNotify,
                                 M_MENU_DISPLAY_TIMER_LEVEL_4,
                                 0,
                                 NULL,
                                 (*Menu_None)},

        [enum_Menu_FactoryFail] = {enum_Menu_FactoryFail,
                                   enum_Menu_SystemSleep,
                                   enum_Window_NoResponseNotify,
                                   M_MENU_DISPLAY_TIMER_LEVEL_2,
                                   0,
                                   NULL,
                                   (*Menu_None)},

        [enum_Menu_FingerVerifyOK] = {enum_Menu_FingerVerifyOK,
                                      enum_Menu_BackDeal,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_15,
                                      0,
                                      NULL,
                                      (*Menu_None)},

        [enum_Menu_FingerVerifyFail] = {enum_Menu_FingerVerifyFail,
                                        enum_Menu_SystemSleep,
                                        enum_Window_NoResponseNotify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)},

        [enum_Menu_OpenLock] = {enum_Menu_OpenLock,
                                enum_Menu_Desktop,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_10,
                                0,
                                NULL,
                                (*Menu_None)},
		[enum_Menu_CloseLockConfirm] = {enum_Menu_CloseLockConfirm,
										enum_Menu_SystemSleep,
										enum_Window_GeneralDialog,
										M_MENU_DISPLAY_TIMER_LEVEL_10,
										0,
										NULL,
										(*Menu_None)},
        [enum_Menu_CloseLock] = {enum_Menu_CloseLock,
                                 enum_Menu_Desktop,
                                 enum_Window_NoResponseNotify,
                                 M_MENU_DISPLAY_TIMER_LEVEL_10,
                                 0,
                                 NULL,
                                 (*Menu_None)},
        [enum_Menu_CloseLockSuccess] = {enum_Menu_CloseLockSuccess,
                                        enum_Menu_BackDeal,
                                        enum_Window_NoResponseNotify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)},
        [enum_Menu_OpenLockSuccess] = {enum_Menu_OpenLockSuccess,
                                       enum_Menu_BackDeal,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_2,
                                       0,
                                       NULL,
                                       (*Menu_None)},
        [enum_Menu_CommError] = {enum_Menu_CommError,
                                 enum_Menu_SystemSleep,
                                 enum_Window_NoResponseNotify,
                                 M_MENU_DISPLAY_TIMER_LEVEL_2,
                                 0,
                                 NULL,
                                 (*Menu_None)},
        [enum_Menu_PryAlarm] = {enum_Menu_PryAlarm,
                                enum_Menu_BackDeal,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_FOREVER,
                                0,
                                NULL,
                                (*Menu_None)},
        [enum_Menu_TryAlarm] = {enum_Menu_TryAlarm,
                                enum_Menu_BackDeal,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_4,
                                0,
                                NULL,
                                (*Menu_None)},
		[enum_Menu_TestError] = {enum_Menu_TestError,
                                enum_Menu_TestErrorReport,
                                enum_Window_NoResponseNotify,
                                M_MENU_DISPLAY_TIMER_LEVEL_6,
                                0,
                                NULL,
                                (*Menu_None)},
		[enum_Menu_TestErrorReport] = {enum_Menu_TestErrorReport,
										enum_Menu_SystemSleep,
										enum_Window_NoResponseNotify,
										M_MENU_DISPLAY_TIMER_LEVEL_4,
										0,
										NULL,
										(*Menu_None)},
		[enum_Menu_Bell] = {enum_Menu_Bell,
							enum_Menu_CatEyeDisConn,
							enum_Window_OnlyReturn,
							M_MENU_DISPLAY_TIMER_FOREVER,
							0,
							NULL,
							(*Menu_None)},
		[enum_Menu_BellCanNotConn] = {enum_Menu_BellCanNotConn,
										enum_Menu_SystemSleep,
										enum_Window_NoResponseNotify,
										M_MENU_DISPLAY_TIMER_LEVEL_1,
										0,
										NULL,
										(*Menu_None)},
		[enum_Menu_WifiConnect] = {enum_Menu_WifiConnect,
										enum_Menu_Desktop,
										enum_Window_NoResponseNotify,
										M_MENU_DISPLAY_TIMER_LEVEL_20,
										0,
										NULL,
										(*Menu_None)},
		[enum_Menu_CatEyeConn] = {enum_Menu_CatEyeConn,
										enum_Menu_CatEyeDisConn,
										enum_Window_OnlyReturn,
										M_MENU_DISPLAY_TIMER_FOREVER,
										0,
										NULL,
										(*Menu_None)},
		[enum_Menu_CatEyeDisConn] = {enum_Menu_CatEyeDisConn,
										enum_Menu_SystemSleep,
										enum_Window_NoResponseNotify,
										M_MENU_DISPLAY_TIMER_LEVEL_1,
										0,
										NULL,
										(*Menu_None)},
        [enum_Menu_KeyDefAlarm] = { enum_Menu_KeyDefAlarm,
                                    enum_Menu_SystemSleep,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_15,
                                    0,
                                    NULL,
                                    (*Menu_None)},
        [enum_Menu_ActiveDefense] = { enum_Menu_ActiveDefense,
                                    enum_Menu_SystemSleep,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_10,
                                    0,
                                    NULL,
                                    (*Menu_None)},
        [enum_Menu_APPMode] = {enum_Menu_APPMode,
                               enum_Menu_BackDeal,
                               enum_Window_NoResponseNotify,
                               M_MENU_DISPLAY_TIMER_LEVEL_60,
                               0,
                               NULL,
                               (*Menu_None)},
        [enum_Menu_BleEquipmentReg] = {enum_Menu_BleEquipmentReg,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_10,
                                       0,
                                       NULL,
                                       (*Menu_None)},
        [enum_Menu_BleAddFingerStep1] = {enum_Menu_BleAddFingerStep1,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerStep1OK] = {enum_Menu_BleAddFingerStep1OK,
                                           enum_Menu_BleAddFingerFail,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerStep2] = {enum_Menu_BleAddFingerStep2,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerStep2OK] = {enum_Menu_BleAddFingerStep2OK,
                                           enum_Menu_BleAddFingerFail,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerStep3] = {enum_Menu_BleAddFingerStep3,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerStep3OK] = {enum_Menu_BleAddFingerStep3OK,
                                           enum_Menu_BleAddFingerFail,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerStep4] = {enum_Menu_BleAddFingerStep4,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerStep4OK] = {enum_Menu_BleAddFingerStep4OK,
                                           enum_Menu_BleAddFingerFail,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerStep5] = {enum_Menu_BleAddFingerStep5,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerStep5OK] = {enum_Menu_BleAddFingerStep5OK,
                                           enum_Menu_BleAddFingerFail,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerStep6] = {enum_Menu_BleAddFingerStep6,
                                         enum_Menu_BleAddFingerFail,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_10,
                                         0,
                                         NULL,
                                         (*Menu_None)},
        [enum_Menu_BleAddFingerOK] = {enum_Menu_BleAddFingerOK,
                                      enum_Menu_APPMode,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_2,
                                      0,
                                      NULL,
                                      (*Menu_None)},
        [enum_Menu_BleAddFingerFail] = {enum_Menu_BleAddFingerFail,
                                        enum_Menu_APPMode,
                                        enum_Window_NoResponseNotify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)},
        [enum_Menu_BleAddFingerConfirm] = {enum_Menu_BleAddFingerConfirm,
                                           enum_Menu_APPMode,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleAddFingerConfirmFail] = {enum_Menu_BleAddFingerConfirmFail,
                                           enum_Menu_APPMode,
                                           enum_Window_NoResponseNotify,
                                           M_MENU_DISPLAY_TIMER_LEVEL_4,
                                           0,
                                           NULL,
                                           (*Menu_None)},
        [enum_Menu_BleFingerDelId] = {enum_Menu_BleFingerDelId,
                                      enum_Menu_APPMode,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_2,
                                      0,
                                      NULL,
                                      (*Menu_None)},
        [enum_Menu_BleAddFaceStep1] = {enum_Menu_BleAddFaceStep1,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_20,
                                       0,
                                       NULL,
                                       (*Menu_None)},
        [enum_Menu_BleAddFaceStep1OK] = {enum_Menu_BleAddFaceStep1OK,
                                         enum_Menu_APPMode,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_4,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //蓝牙人脸过程成功

        [enum_Menu_BleAddFaceStep2] = {enum_Menu_BleAddFaceStep2,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_20,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //蓝牙人脸过程

        [enum_Menu_BleAddFaceStep2OK] = {enum_Menu_BleAddFaceStep2OK,
                                         enum_Menu_APPMode,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_4,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //蓝牙人脸过程成功

        [enum_Menu_BleAddFaceStep3] = {enum_Menu_BleAddFaceStep3,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_20,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //蓝牙人脸过程

        [enum_Menu_BleAddFaceStep3OK] = {enum_Menu_BleAddFaceStep3OK,
                                         enum_Menu_APPMode,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_4,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //蓝牙人脸过程成功

        [enum_Menu_BleAddFaceStep4] = {enum_Menu_BleAddFaceStep4,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_20,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //蓝牙人脸过程

        [enum_Menu_BleAddFaceStep4OK] = {enum_Menu_BleAddFaceStep4OK,
                                         enum_Menu_APPMode,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_4,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //蓝牙人脸过程成功

        [enum_Menu_BleAddFaceStep5] = {enum_Menu_BleAddFaceStep5,
                                       enum_Menu_APPMode,
                                       enum_Window_NoResponseNotify,
                                       M_MENU_DISPLAY_TIMER_LEVEL_20,
                                       0,
                                       NULL,
                                       (*Menu_None)}, //蓝牙人脸过程

        [enum_Menu_BleAddFaceStep5OK] = {enum_Menu_BleAddFaceStep5OK,
                                         enum_Menu_APPMode,
                                         enum_Window_NoResponseNotify,
                                         M_MENU_DISPLAY_TIMER_LEVEL_4,
                                         0,
                                         NULL,
                                         (*Menu_None)}, //蓝牙人脸过程5成功

        [enum_Menu_BleAddFaceUserOk] = {enum_Menu_BleAddFaceUserOk,
                                        enum_Menu_APPMode,
                                        enum_Window_NoResponseNotify,
                                        M_MENU_DISPLAY_TIMER_LEVEL_2,
                                        0,
                                        NULL,
                                        (*Menu_None)}, //蓝牙人脸成功

        [enum_Menu_BleAddFaceUserFail] = {enum_Menu_BleAddFaceUserFail,
                                          enum_Menu_APPMode,
                                          enum_Window_NoResponseNotify,
                                          M_MENU_DISPLAY_TIMER_LEVEL_2,
                                          0,
                                          NULL,
                                          (*Menu_None)}, //蓝牙人脸失败
        [enum_Menu_BleAddFaceUserConfirm] = {enum_Menu_BleAddFaceUserConfirm,
                                             enum_Menu_APPMode,
                                             enum_Window_NoResponseNotify,
                                             M_MENU_DISPLAY_TIMER_LEVEL_2,
                                             0,
                                             NULL,
                                             (*Menu_None)}, //
        [enum_Menu_BleFaceDelId] = {enum_Menu_BleFaceDelId,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_10,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //
		[enum_Menu_BleDelFinger] = {enum_Menu_BleDelFinger,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_2,
                                    0,
                                    NULL,
                                    (*Menu_None)}, //
		[enum_Menu_BleEmptyUser] = {enum_Menu_BleEmptyUser,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_10,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleFaceVersionGet] = {enum_Menu_BleFaceVersionGet,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_10,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleConfigWifiData] = {enum_Menu_BleConfigWifiData,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_60,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleAliyunSecretKeySetParm] = {enum_Menu_BleAliyunSecretKeySetParm,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_60,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleCatEyeSN] = {enum_Menu_BleCatEyeSN,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_60,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleShangTangCatEyeSingleDouble] = {enum_Menu_BleShangTangCatEyeSingleDouble,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_LEVEL_60,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleR8CatEyeOTA] = {enum_Menu_BleR8CatEyeOTA,
                                    enum_Menu_APPMode,
                                    enum_Window_NoResponseNotify,
                                    M_MENU_DISPLAY_TIMER_FOREVER,
                                    0,
                                    NULL,
                                    (*Menu_None)}, 
		[enum_Menu_BleVerifyPhoneEncryptSuccess] = {enum_Menu_BleVerifyPhoneEncryptSuccess,
                                      enum_Menu_BackDeal,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_15,
                                      0,
                                      NULL,
                                      (*Menu_None)},
		[enum_Menu_BleToolTestFail] = {enum_Menu_BleToolTestFail,
                                      enum_Menu_APPMode,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_30,
                                      0,
                                      NULL,
                                      (*Menu_None)},
		[enum_Menu_BleUnlockSmartKeyVerifySuccess] = {enum_Menu_BleUnlockSmartKeyVerifySuccess,
                                      enum_Menu_BackDeal,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_15,
                                      0,
                                      NULL,
                                      (*Menu_None)},
		[enum_Menu_BleUnlockSmartKeyVerifyFail] = {enum_Menu_BleUnlockSmartKeyVerifyFail,
                                      enum_Menu_BackDeal,
                                      enum_Window_NoResponseNotify,
                                      M_MENU_DISPLAY_TIMER_LEVEL_15,
                                      0,
                                      NULL,
                                      (*Menu_None)},
		[enum_Menu_BleModifFaceSafetyLevel] = {enum_Menu_BleModifFaceSafetyLevel,
												enum_Menu_APPMode,
												enum_Window_NoResponseNotify,
												M_MENU_DISPLAY_TIMER_LEVEL_60,
												0,
												NULL,
												(*Menu_None)}, 
		[enum_Menu_BleInfraredMonitoringDistanceSet] = {enum_Menu_BleInfraredMonitoringDistanceSet,
												enum_Menu_APPMode,
												enum_Window_NoResponseNotify,
												M_MENU_DISPLAY_TIMER_LEVEL_60,
												0,
												NULL,
												(*Menu_None)}, 
};

TYPEs_InputInfo st_InputInfo = {
    .a_u8_PassWordBuf = {
        0x00,
    },                     //密码输入存放区，用户ID缓存区
    .u8_PassWordBytes = 0, //密码输入字节数
    .a_u8_PassWordBufBak = {
        0x00,
    },                         //密码输入存放区备份
    .u8_PassWordBytesBak = 0,  //密码输入字节数备份
    .enterProjectModeCnt = 0,  //进入工程模式验证过程
    .enterProjectModeFlag = 0, //进入工程模式标志
    .adminReg = 0,             //本地管理员注册情况
    .FingerIdTmp = 0,          //指纹头ID临时存储
    .userType = eUserTypePWD,  //用户类型 0,密码，1指纹
    .userID = 0,               //用户ID
                               //	.wakeUpSource=0,				  //唤醒源
#if defined(KEY_RANDOM_LOCK_EN)
    .keyRandomSetFlag = ekeyRandomSetEnable,       //随机按键生成标志
    .keyRandomLockFlag = eKeyRandomLockFlagEnable, //随机按键标志
    .keyRandom = {
        0,
    }, //用于保存用户随机数
#endif // KEY_RANDOM_LOCK_EN
    //	TYPEs_ErrorCnt errorCnt=0,					 //错误次数
    //	struct tm RTCTimer=0,							 //Rtc时间
    .emptyFace = eEquipResultNone,        //清空人脸结果
    .emptyFinger = eEquipResultNone,      //清空指纹结果
    .TimeCnt = 0,                         //操作计时器
    .bellOutTimeCnt = 0,                  //门铃操作计数器
    .pryAlarmEnableFlag = 0,              //报警使能
    .pryAlarmFlag = 0,                    //报警之前的状态
    .pryAlarmTimeCnt = 0,                 //报警时间计数
    .upBatBattery = 0,                    //上方电池电量
    .downBatBattery = 0,                  //下方电池电量
    .openKey = 0,                         //开门键盘值
    .closeKey = 0,                        //关门键盘值
    .appMode = eAPPModeNone,              //APP模式
    .storageStatus = eStorageStatusError, //存储状态
    .iD2Status = eID2StatusError,         //ID2状态
    .bleMac = {
        0,
    },                          //蓝牙MAC
    .u8_EnterAdminFlag = 0,     //是否有按*键
    .u8_EnterAdminFlagBak = 0,  //是否有按*键备份
    .u16_PreHandleStatus = 0,   //记录前一次的执手状态
    .u8_UserId = 0,             //用户ID 00~99 -1表示编号无效
    .u8_UserIdBak = 0,          //用户ID 00~99 备份
    .u8_CurrentPermission = 0,  //当前所在开锁权限，0：普通，1：管理员
    .u16_Battery_Indicator = 0, //当前的电量
    .u8_Debug_Status = 0,       //调试状态
    .a_u8_CommandBuf = {
        0,
    },                                    //指令输入存放区，用户ID缓存区
    .u8_CommandBytes = 0,                 //指令输入字节数
    .KeepTimeUpdateDisableFlag = 0,       //菜单持续时间使能标志，0，使能，1失能
    .ShutDownStep = enumShutDownStepNone, //待机处理步骤
    .modeuleFail.reserved = 0,
    .modeuleFail.RTC = 0,
    .modeuleFail.reserved1 = 0,
    .modeuleFail.Finger = 0,
    .modeuleFail.Face = 0,
    .modeuleFail.reserved2 = 0,
    .modeuleFail.Ir = 0,
    .modeuleFail.Wifi = 0,
}; //用户输入的信息
/*************************局部函数*****************************/

/*************************全局函数****************************/
#endif
/************************************Code End******************************************/
